import "./globals.css";
import { AuthProvider } from "@/provider/AuthProvider";

export const metadata = {
  title: "lein-dein",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
